# Tarea día 8
**Programación I**  
**Helen Saraí Avila Cabrera**

## Ejercicio 1

Cree una matriz que contenga ceros. Rellene la mitad de ellos aleatoriamente con unos.

In [2]:
import numpy as np

In [3]:
import random

In [4]:
fila=3 #Número que ingresa el usuario, correspondiente al número de filas.
columna=5 #Número que ingresa el usuario, correspondiente al número de columnas. 
x=fila*columna #Se calcula el número de ceros a crear. 

a = np.zeros((x), dtype=int) #Se crea una lista de ceros de longitud:x
y = int(x/2) #Se calcula la mitad de la lista 
a[:y]=1 #Se asigna a la mitad de la lista el valor de uno. 
np.random.shuffle(a) #Con la función de shuffle random se reordena la matriz de forma aleatoria. 

print(a.reshape(fila,columna)) #Se reordena la matriz como una matriz cuadrada  

[[1 1 0 1 0]
 [0 0 0 0 1]
 [0 1 1 1 0]]


## Ejercicio 2
Cree dos matrices de dimensiones $(5,2)$. La primera rellena de ceros y la siguiente de unos. 
1.	Convierta las matrices en vectores columna. 
2.	Apile ambos vectores a lo largo de una tercera dimensión. 
3.	Con las matrices originales, conviértalas en vectores fila y concaténelos verticalmente. 



#### Inciso 1: Convierta las matrices en vectores columna. 

In [307]:
a = np.zeros((5,2), dtype=int)
print(a)

[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]


In [308]:
b = np.ones((5,2), dtype=int)
print(b)

[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]


In [309]:
vec_a = a.flatten()
col_a = vec_a[:,None]
print(col_a)

[[0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]]


In [310]:
vec_b = b.flatten()
col_b = vec_b[:,None]
print(col_b)

[[1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]]


#### Inciso 2: Apile ambos vectores a lo largo de una tercera dimensión. 

In [311]:
c = np.dstack([col_a,col_b])
print(c)

[[[0 1]]

 [[0 1]]

 [[0 1]]

 [[0 1]]

 [[0 1]]

 [[0 1]]

 [[0 1]]

 [[0 1]]

 [[0 1]]

 [[0 1]]]


#### Inciso 3: Con las matrices originales, conviértalas en vectores fila y concaténelos verticalmente. 

In [316]:
vec_a = a.flatten()
vec_b = b.flatten()

In [313]:
d = np.concatenate((vec_a[:,None], vec_b[:,None]), axis=0)
print(d)

[[0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]]


## Ejercicio 3

Dada la función $f(x,y,z) = 2x +3y + z^2$
1.	Genere una matriz con números aleatorios para cada variable. 
2.	Evalúe la matriz anterior en la función. El resultado debe ser un vector columna. 

In [314]:
def f(matriz):
    return 2*matriz[:,0] + 3*matriz[:,1] + matriz[:,2]**2

In [315]:
x = 5 #Número que puede ser ingresado por el usuario para determinar el número de filas de la matriz. 
matriz = np.floor ( 10 * np.random.random ((x,3))) #El número de columnas de la matriz de número aleatorios debe de ser 3. 
print(f(matriz)[:,None])

[[34.]
 [41.]
 [58.]
 [81.]
 [29.]]


## Ejercicio 4

Suponga que dentro de un cuadrado de lado 50 cm, hay un cuadrado de 20cm. Ambos cuadrados comparten centro. Estime el área del cuadrado interno por método Monte Carlo. [Consulte Aquí]( http://mathonweb.com/entrtain/monte/t_monte.htm)

In [26]:
c50 = np.random.randint(2, size=(50, 50)) #Se crea una matriz 50x50 llena de 1 y 0.
total = (c50 == 1).sum() #Se cuenta la cantidad de unos en la matriz 50x50.

c20 = c50[15:35, 15:35] #Se utiliza slicing para generar una matriz 20x20.
adentro = (c20 == 1).sum() #De igual manera se cuentan la cantidad de unos en dicha matriz.

area = (50**2)*(adentro/total) #Se utiliza la igualdad, conociendo a priori el area del cuadrado de 50cm.

print(area)

399.6802557953637


In [22]:
c50 = np.random.randint(2, size=(50, 50))
print(c50)

[[1 0 1 ... 0 1 0]
 [1 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 1]
 ...
 [1 1 0 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 1]]


In [19]:
c20 = c50[15:35, 15:35]
print(c20)

[[1 1 0 1 1 1 0 0 1 0 1 0 1 1 0 1 1 0 1 0]
 [0 0 0 1 1 0 0 1 0 1 1 1 1 0 1 0 1 1 0 0]
 [0 1 0 0 0 0 0 1 1 1 1 0 0 1 1 1 1 1 1 0]
 [1 1 0 1 0 0 0 1 1 1 0 0 0 0 1 1 1 1 1 0]
 [1 0 0 1 0 1 0 1 0 1 1 0 0 1 0 1 0 1 1 1]
 [0 0 1 1 0 1 1 0 1 1 0 1 1 0 0 0 0 0 1 1]
 [1 0 0 1 1 1 1 1 1 0 1 0 0 0 1 1 0 0 1 0]
 [1 0 1 1 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0]
 [1 1 0 0 1 0 1 0 1 0 0 0 0 1 1 1 1 0 0 1]
 [0 0 1 1 1 1 1 0 1 1 0 0 0 0 1 0 0 0 1 1]
 [0 1 0 1 0 1 1 0 1 0 0 1 1 1 1 0 0 0 0 1]
 [0 0 1 0 1 1 0 0 0 1 1 1 1 1 1 0 0 1 1 0]
 [0 1 0 1 1 1 0 1 1 1 0 0 0 0 1 1 0 0 1 1]
 [1 0 0 0 1 0 1 0 0 0 1 1 1 0 0 1 0 0 0 1]
 [1 0 0 1 0 1 1 1 1 1 1 0 0 1 1 0 0 1 1 1]
 [0 1 0 0 1 0 0 1 0 0 1 1 1 0 1 0 0 1 1 1]
 [0 1 0 1 1 1 1 0 1 1 1 0 0 0 0 1 0 1 0 1]
 [0 1 1 1 0 0 1 1 1 0 0 1 0 0 1 0 1 1 0 1]
 [1 0 0 0 1 0 1 1 0 0 0 1 0 1 1 1 1 0 0 1]
 [0 0 0 0 1 0 0 0 0 0 1 1 0 1 0 1 0 1 0 1]]


## Ejercicio 5

### *Tarea*

1. De las siguientes secciones, escoger 73 funciones de NumPy y mostrar su utilización en un ejemplo.

    - [Array creation routines](https://numpy.org/devdocs/reference/routines.array-creation.html)

    - [Array manipulation routines](https://numpy.org/devdocs/reference/routines.array-manipulation.html)

    - [Binary operations](https://numpy.org/devdocs/reference/routines.bitwise.html)

    - [String operations](https://numpy.org/devdocs/reference/routines.char.html)
    

2. Crear un ejemplo de cómo guardar y cargar arreglos de un archivo binario `.npy` y `.npz`:

    - [NumPy binary files (NPY, NPZ)](https://numpy.org/devdocs/reference/routines.io.html#numpy-binary-files-npy-npz)
    
3. Crear un ejemplo de cómo guardar y cargar arreglos de un archivo de texto `.txt`:

    - [NumPy Text files](https://numpy.org/devdocs/reference/routines.io.html#text-files)    
    
4. Crear una función llamada `estimacionMCO` que lea un archivo CSV con 7 columnas, que corresponden a las variables $(x_{1i}, \ldots, x_{6i})$ y $y_i$. 
    - La función debe computar matricialmente los parámetros del modelo de regresión lineal: $y = X\beta$. 
    - Estos parámetros deben ser devueltos como un arreglo de NumPy. 

    - Utilice la función de lectura de archivos de NumPy.

### Ones and zeros:

In [5]:
#Funcion 1: 
#empty(shape[, dtype, order])
#Return a new array of given shape and type, without initializing entries.
np.empty([2, 2])


array([[-2.31584178e+077, -2.31584178e+077],
       [ 1.69759663e-313,  0.00000000e+000]])

In [6]:
#Funcion 2:
#empty_like(prototype[, dtype, order, subok, …])
#Return a new array with the same shape and type as a given array.
a = ([1,2,3], [4,5,6])                     
np.empty_like(a)

array([[-3458764513820540928, -3458764513820540928, -9223372036854775782],
       [                   0,        1103806595328,                  256]])

In [7]:
#Funcion 3:
#eye(N[, M, k, dtype, order])
#Return a 2-D array with ones on the diagonal and zeros elsewhere.
np.eye(2, dtype=int)

array([[1, 0],
       [0, 1]])

In [8]:
#Funcion 4:
#identity(n[, dtype])
#Return the identity array.
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
#Funcion 5:
#ones(shape[, dtype, order])
#Return a new array of given shape and type, filled with ones.
np.ones((5,), dtype=int)

array([1, 1, 1, 1, 1])

In [10]:
#Funcion 6:
#ones_like(a[, dtype, order, subok, shape])
#Return an array of ones with the same shape and type as a given array.
x = np.arange(6)
x = x.reshape((2, 3))
x

array([[0, 1, 2],
       [3, 4, 5]])

In [12]:
#Funcion 7:
#zeros(shape[, dtype, order])
#Return a new array of given shape and type, filled with zeros.
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
#Funcion 8:
#zeros_like(a[, dtype, order, subok, shape])
#Return an array of zeros with the same shape and type as a given array.
x = np.arange(6)
x = x.reshape((2, 3))
x

array([[0, 1, 2],
       [3, 4, 5]])

In [14]:
#Funcion 9:
#full(shape, fill_value[, dtype, order])
#Return a new array of given shape and type, filled with fill_value.
np.full((2, 2), np.inf)

array([[inf, inf],
       [inf, inf]])

In [15]:
#Funcion 10:
#full_like(a, fill_value[, dtype, order, …])
#Return a full array with the same shape and type as a given array.
x = np.arange(6, dtype=int)
np.full_like(x, 1)

array([1, 1, 1, 1, 1, 1])

### From existing data:

In [16]:
#Funcion 11:
#array(object[, dtype, copy, order, subok, ndmin])
#Create an array.
np.array([1, 2, 3])

array([1, 2, 3])

In [18]:
#Funcion 12:
#asarray(a[, dtype, order])
#Convert the input to an array.
a = [1, 2]
np.asarray(a)

array([1, 2])

In [19]:
#Funcion 13:
#asanyarray(a[, dtype, order])
#Convert the input to an ndarray, but pass ndarray subclasses through.
a = [1, 2]
np.asanyarray(a)

array([1, 2])

In [20]:
#Funcion 14:
#ascontiguousarray(a[, dtype])
#Return a contiguous array (ndim >= 1) in memory (C order).
x = np.arange(6).reshape(2,3)
np.ascontiguousarray(x, dtype=np.float32)

array([[0., 1., 2.],
       [3., 4., 5.]], dtype=float32)

In [24]:
#Funcion 15:
#asmatrix(data[, dtype])
#Interpret the input as a matrix.
x = np.array([[1, 2], [3, 4]])
m = np.asmatrix(x)
x[0,0] = 5
m

matrix([[5, 2],
        [3, 4]])

In [26]:
#Funcion 16:
#copy(a[, order])
#Return an array copy of the given object.
x = np.array([1, 2, 3])
y = x
z = np.copy(x)
z

array([1, 2, 3])

In [27]:
#Funcion 17:
#frombuffer(buffer[, dtype, count, offset])
#Interpret a buffer as a 1-dimensional array.
s = b'hello world'
np.frombuffer(s, dtype='S1', count=5, offset=6)

array([b'w', b'o', b'r', b'l', b'd'], dtype='|S1')

In [119]:
#Funcion 18:
#vsplit(ary, indices_or_sections)
#Split an array into multiple sub-arrays vertically (row-wise).
x = np.arange(16.0).reshape(4, 4)
x

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [120]:
np.vsplit(x, 2)

[array([[0., 1., 2., 3.],
        [4., 5., 6., 7.]]), array([[ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]])]

In [28]:
#Funcion 19:
#fromfunction(function, shape, \*[, dtype])
#Construct an array by executing a function over each coordinate.
np.fromfunction(lambda i, j: i == j, (3, 3), dtype=int)

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [29]:
#Funcion 20:
#fromiter(iterable, dtype[, count])
#Create a new 1-dimensional array from an iterable object.
iterable = (x*x for x in range(5))
np.fromiter(iterable, float)

array([ 0.,  1.,  4.,  9., 16.])

In [30]:
#Funcion 20:
#fromstring(string[, dtype, count, sep])
#A new 1-D array initialized from text data in a string.
np.fromstring('1 2', dtype=int, sep=' ')

array([1, 2])

In [31]:
#Funcion 20:
#loadtxt(fname[, dtype, comments, delimiter, …])
#Load data from a text file.
from io import StringIO   # StringIO behaves like a file object
c = StringIO(u"0 1\n2 3")
np.loadtxt(c)

array([[0., 1.],
       [2., 3.]])

### Creating record arrays (numpy.rec)

In [117]:
#Funcion 20:
#hsplit(ary, indices_or_sections)
#Split an array into multiple sub-arrays horizontally (column-wise).
x = np.arange(16.0).reshape(4, 4)
x

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [118]:
np.hsplit(x, 2)

[array([[ 0.,  1.],
        [ 4.,  5.],
        [ 8.,  9.],
        [12., 13.]]), array([[ 2.,  3.],
        [ 6.,  7.],
        [10., 11.],
        [14., 15.]])]

In [35]:
#Funcion 21:
#core.records.fromarrays(arrayList[, dtype, …])
#create a record array from a (flat) list of arrays
x1=np.array([1,2,3,4])
x2=np.array(['a','dd','xyz','12'])
x3=np.array([1.1,2,3,4])
r = np.core.records.fromarrays([x1,x2,x3],names='a,b,c')
print(r[1])

(2, 'dd', 2.)


In [37]:
x1[1]=34
r.a

array([1, 2, 3, 4])

In [112]:
#Funcion 22:
#vstack(tup)
#Stack arrays in sequence vertically (row wise).
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])
np.vstack((a,b))

array([[1, 2, 3],
       [2, 3, 4]])

In [114]:
#Funcion 23:
#block(arrays)
#semble an nd-array from nested lists of blocks.
A = np.ones((2, 2), int)
B = 2 * A
np.block([A, B])

array([[1, 1, 2, 2],
       [1, 1, 2, 2]])

In [113]:
#Funcion 24:
#split(ary, indices_or_sections[, axis])
#Split an array into multiple sub-arrays as views into ary.
x = np.arange(9.0)
np.split(x, 3)

[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7., 8.])]

### Creating character arrays (numpy.char)

In [115]:
#Funcion 25:
#array_split(ary, indices_or_sections[, axis])
#Split an array into multiple sub-arrays.
x = np.arange(8.0)
np.array_split(x, 3)

[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7.])]

In [116]:
#Funcion 26:
#dsplit(ary, indices_or_sections)
#Split array into multiple sub-arrays along the 3rd axis (depth).
x = np.arange(16.0).reshape(2, 2, 4)
np.dsplit(x, 2)

[array([[[ 0.,  1.],
         [ 4.,  5.]],
 
        [[ 8.,  9.],
         [12., 13.]]]), array([[[ 2.,  3.],
         [ 6.,  7.]],
 
        [[10., 11.],
         [14., 15.]]])]

### Numerical ranges

In [38]:
#Funcion 27:
#arange([start,] stop[, step,][, dtype])
#Return evenly spaced values within a given interval.
np.arange(3,7)

array([3, 4, 5, 6])

In [39]:
#Funcion 28:
#linspace(start, stop[, num, endpoint, …])
#Return evenly spaced numbers over a specified interval.
np.linspace(2.0, 3.0, num=5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [40]:
#Funcion 29:
#logspace(start, stop[, num, endpoint, base, …])
#Return numbers spaced evenly on a log scale.
np.logspace(2.0, 3.0, num=4)

array([ 100.        ,  215.443469  ,  464.15888336, 1000.        ])

In [41]:
#Funcion 30:
#geomspace(start, stop[, num, endpoint, …])
#Return numbers spaced evenly on a log scale (a geometric progression).
np.geomspace(1, 1000, num=4)

array([   1.,   10.,  100., 1000.])

In [44]:
#Funcion 31:
#meshgrid(\*xi[, copy, sparse, indexing])
#Return coordinate matrices from coordinate vectors.
nx, ny = (3, 2)
x = np.linspace(0, 1, nx)
y = np.linspace(0, 1, ny)
xv, yv = np.meshgrid(x, y)
xv

array([[0. , 0.5, 1. ],
       [0. , 0.5, 1. ]])

In [45]:
#Funcion 32:
#mgrid
#nd_grid instance which returns a dense multi-dimensional “meshgrid”.
np.mgrid[0:5,0:5]

array([[[0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3],
        [4, 4, 4, 4, 4]],

       [[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]]])

In [47]:
#Funcion 33:
#ogrid
#nd_grid instance which returns an open multi-dimensional “meshgrid”.
from numpy import ogrid
ogrid[-1:1:5j]

array([-1. , -0.5,  0. ,  0.5,  1. ])

### Building matrices

In [50]:
#Funcion 34:
#diag(v[, k])
#Extract a diagonal or construct a diagonal array.
x = np.arange(9).reshape((3,3))
print(x)
np.diag(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([0, 4, 8])

In [51]:
#Funcion 35:
#diagflat(v[, k])
#Create a two-dimensional array with the flattened input as a diagonal.
np.diagflat([[1,2], [3,4]])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [52]:
#Funcion 36:
#tri(N[, M, k, dtype])
#An array with ones at and below the given diagonal and zeros elsewhere.
np.tri(3, 5, 2, dtype=int)

array([[1, 1, 1, 0, 0],
       [1, 1, 1, 1, 0],
       [1, 1, 1, 1, 1]])

In [53]:
#Funcion 37:
#tril(m[, k])
#Lower triangle of an array.
np.tril([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], -1)

array([[ 0,  0,  0],
       [ 4,  0,  0],
       [ 7,  8,  0],
       [10, 11, 12]])

In [56]:
#Funcion 38:
#triu(m[, k])
#Upper triangle of an array.
np.triu([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], -1)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 0,  8,  9],
       [ 0,  0, 12]])

In [54]:
#Funcion 39:
#vander(x[, N, increasing])
#Generate a Vandermonde matrix.
x = np.array([1, 2, 3, 5])
N = 3
np.vander(x, N)

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [25,  5,  1]])

### The Matrix class

In [58]:
#Funcion 40:
#mat(data[, dtype])
#Interpret the input as a matrix.
x = np.array([[1, 2], [3, 4]])
m = np.asmatrix(x)
x[0,0] = 5
m


matrix([[5, 2],
        [3, 4]])

In [59]:
#Funcion 41:
#bmat(obj[, ldict, gdict])
#Build a matrix object from a string, nested sequence, or array.
A = np.mat('1 1; 1 1')
B = np.mat('2 2; 2 2')
C = np.mat('3 4; 5 6')
D = np.mat('7 8; 9 0')

np.bmat([[A, B], [C, D]])


matrix([[1, 1, 2, 2],
        [1, 1, 2, 2],
        [3, 4, 7, 8],
        [5, 6, 9, 0]])

In [61]:
np.bmat(np.r_[np.c_[A, B], np.c_[C, D]])

matrix([[1, 1, 2, 2],
        [1, 1, 2, 2],
        [3, 4, 7, 8],
        [5, 6, 9, 0]])

In [60]:
np.bmat('A,B; C,D')

matrix([[1, 1, 2, 2],
        [1, 1, 2, 2],
        [3, 4, 7, 8],
        [5, 6, 9, 0]])

## Array Manipulation rutines

### Basic operations

In [110]:
#Funcion 42:
#hstack(tup)
#Stack arrays in sequence horizontally (column wise).
a = np.array((1,2,3))
b = np.array((2,3,4))
np.hstack((a,b))

array([1, 2, 3, 2, 3, 4])

In [63]:
#Funcion 43:
#shape(a)
#Return the shape of an array.
np.shape(np.eye(3))

(3, 3)

### Changing array shape

In [65]:
#Funcion 44:
#reshape(a, newshape[, order])
#Gives a new shape to an array without changing its data.
a = np.arange(6).reshape((3, 2))
np.reshape(a, (2, 3))

array([[0, 1, 2],
       [3, 4, 5]])

In [66]:
#Funcion 45:
#ravel(a[, order])
#Return a contiguous flattened array.
x = np.array([[1, 2, 3], [4, 5, 6]])
np.ravel(x)

array([1, 2, 3, 4, 5, 6])

In [71]:
#Funcion 46:
#ndarray.flat
#A 1-D iterator over the array.
x = np.arange(1, 7).reshape(2, 3)
x

array([[1, 2, 3],
       [4, 5, 6]])

In [70]:
x.flat[3]

4

In [72]:
#Funcion 47:
#ndarray.flatten([order])
#Return a copy of the array collapsed into one dimension.
a = np.array([[1,2], [3,4]])
a.flatten()

array([1, 2, 3, 4])

### Transpose-like operations

In [73]:
#Funcion 48:
#moveaxis(a, source, destination)
#Move axes of an array to new positions.
x = np.zeros((3, 4, 5))
np.moveaxis(x, 0, -1).shape

(4, 5, 3)

In [74]:
#Funcion 49:
#rollaxis(a, axis[, start])
#Roll the specified axis backwards, until it lies in a given position.
a = np.ones((3,4,5,6))
np.rollaxis(a, 3, 1).shape

(3, 6, 4, 5)

In [76]:
#Funcion 50:
#swapaxes(a, axis1, axis2)
#Interchange two axes of an array.
x = np.array([[1,2,3]])
np.swapaxes(x,0,1)

array([[1],
       [2],
       [3]])

In [78]:
#Funcion 51:
#ndarray.T
#The transposed array.
x = np.array([[1.,2.],[3.,4.]])
x

array([[1., 2.],
       [3., 4.]])

In [79]:
#Funcion 52:
#transpose(a[, axes])
#Reverse or permute the axes of an array; returns the modified array.
x = np.arange(4).reshape((2,2))
np.transpose(x)

array([[0, 2],
       [1, 3]])

### Changing number of dimensions

In [80]:
#Funcion 53:
#atleast_1d(\*arys)
#Convert inputs to arrays with at least one dimension.
x = np.arange(9.0).reshape(3,3)
np.atleast_1d(x)

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [81]:
#Funcion 54:
#atleast_2d(\*arys)
#View inputs as arrays with at least two dimensions.
x = np.arange(3.0)
np.atleast_2d(x)

array([[0., 1., 2.]])

In [82]:
#Funcion 55:
#atleast_3d(\*arys)
#View inputs as arrays with at least three dimensions.
x = np.arange(3.0)
np.atleast_3d(x).shape

(1, 3, 1)

In [85]:
#Funcion 56:
#broadcast
#Produce an object that mimics broadcasting.
x = np.array([[1], [2], [3]])
y = np.array([4, 5, 6])
b = np.broadcast(x, y)
out = np.empty(b.shape)
out.flat = [u+v for (u,v) in b]
out

array([[5., 6., 7.],
       [6., 7., 8.],
       [7., 8., 9.]])

In [86]:
#Funcion 57:
#broadcast_to(array, shape[, subok])
#Broadcast an array to a new shape.
x = np.array([1, 2, 3])
np.broadcast_to(x, (3, 3))

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [87]:
#Funcion 58:
#broadcast_arrays(\*args[, subok])
#Broadcast any number of arrays against each other.
x = np.array([[1,2,3]])
y = np.array([[4],[5]])
np.broadcast_arrays(x, y)

[array([[1, 2, 3],
        [1, 2, 3]]), array([[4, 4, 4],
        [5, 5, 5]])]

In [88]:
#Funcion 59:
#expand_dims(a, axis)
#Expand the shape of an array.
y = np.expand_dims(x, axis=0)
y.shape

(1, 1, 3)

In [89]:
#Funcion 60:
#squeeze(a[, axis])
#Remove single-dimensional entries from the shape of an array.
x = np.array([[[0], [1], [2]]])
x.shape
np.squeeze(x).shape

(3,)

### Changing kind of array

In [90]:
#Funcion 61:
#asarray(a[, dtype, order])
#Convert the input to an array.
a = [1, 2]
np.asarray(a)

array([1, 2])

In [91]:
#Funcion 62:
#asanyarray(a[, dtype, order])
#Convert the input to an ndarray, but pass ndarray subclasses through.
a = [1, 2]
np.asanyarray(a)

array([1, 2])

In [92]:
#Funcion 63:
#asmatrix(data[, dtype])
#Interpret the input as a matrix.
x = np.array([[1, 2], [3, 4]])
m = np.asmatrix(x)
x[0,0] = 5
m

matrix([[5, 2],
        [3, 4]])

In [93]:
#Funcion 64:
#asfarray(a[, dtype])
#Return an array converted to a float type.
np.asfarray([2, 3])

array([2., 3.])

In [97]:
#Funcion 65:
#asfortranarray(a[, dtype])
#Return an array (ndim >= 1) laid out in Fortran order in memory.
x = np.arange(6).reshape(2,3)
y = np.asfortranarray(x)
x.flags['F_CONTIGUOUS']

False

In [98]:
y.flags['F_CONTIGUOUS']

True

In [99]:
#Funcion 66:
#ascontiguousarray(a[, dtype])
#Return a contiguous array (ndim >= 1) in memory (C order).
x = np.arange(6).reshape(2,3)
np.ascontiguousarray(x, dtype=np.float32)

array([[0., 1., 2.],
       [3., 4., 5.]], dtype=float32)

In [100]:
#Funcion 67:
#asarray_chkfinite(a[, dtype, order])
#Convert the input to an array, checking for NaNs or Infs.
a = [1, 2]
np.asarray_chkfinite(a, dtype=float)

array([1., 2.])

In [102]:
#Funcion 68:
#asscalar(a)
#Convert an array of size 1 to its scalar equivalent.
np.asscalar(np.array([24]))

/Users/helenavila/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: DeprecationWarning: np.asscalar(a) is deprecated since NumPy v1.16, use a.item() instead
  after removing the cwd from sys.path.


24

In [103]:
#Funcion 69:
#require(a[, dtype, requirements])
#Return an ndarray of the provided type that satisfies requirements.
x = np.arange(6).reshape(2,3)
x.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

### Joining arrays

In [104]:
#Funcion 70:
#concatenate([axis, out])
#Join a sequence of arrays along an existing axis.
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [105]:
#Funcion 71:
#stack(arrays[, axis, out])
#Join a sequence of arrays along a new axis.
arrays = [np.random.randn(3, 4) for _ in range(10)]
np.stack(arrays, axis=0).shape

(10, 3, 4)

In [106]:
#Funcion 72:
#column_stack(tup)
#Stack 1-D arrays as columns into a 2-D array.
a = np.array((1,2,3))
b = np.array((2,3,4))
np.column_stack((a,b))

array([[1, 2],
       [2, 3],
       [3, 4]])

In [109]:
#Funcion 73:
#dstack(tup)
#Stack arrays in sequence depth wise (along third axis).
a = np.array((1,2,3))
b = np.array((2,3,4))
np.dstack((a,b))


array([[[1, 2],
        [2, 3],
        [3, 4]]])

Crear un ejemplo de cómo guardar y cargar arreglos de un archivo binario `.npy` y `.npz`:

    - [NumPy binary files (NPY, NPZ)](https://numpy.org/devdocs/reference/routines.io.html#numpy-binary-files-npy-npz)
    


In [148]:
import numpy as np
x = np.random.random((10,10))
y = np.arange(1,100)

np.savez('EjemploNPY.npz', var_x = x, var_y = y)

In [149]:
Data=np.load('EjemploNPY.bin.npz')

In [150]:
Data['var_x']

array([[9.70070686e-01, 6.94248312e-01, 7.89483063e-01, 2.71679818e-01,
        3.56442382e-03, 9.77727285e-02, 5.41394536e-01, 5.84577459e-01,
        8.38453098e-01, 2.28120385e-01],
       [8.43878286e-01, 5.36565607e-01, 1.02909135e-01, 8.26359500e-01,
        6.23899012e-01, 3.09326106e-02, 9.04196999e-01, 6.77549700e-01,
        8.35698381e-01, 8.21021742e-01],
       [8.84819959e-01, 6.43180946e-02, 9.69412559e-01, 8.98434595e-01,
        8.88789329e-01, 7.74448574e-03, 5.53639554e-01, 5.79622565e-01,
        6.53587773e-01, 1.37880268e-02],
       [4.59380578e-01, 8.40245829e-01, 6.59500771e-01, 4.67368714e-02,
        8.06233037e-01, 7.27871499e-01, 4.19526405e-01, 5.65227124e-01,
        6.71130051e-01, 5.87463849e-01],
       [5.57159716e-01, 5.56770028e-01, 1.78622801e-01, 2.24401697e-01,
        3.93502930e-01, 1.72574323e-01, 3.11650024e-01, 2.45506355e-01,
        3.56604510e-01, 3.67181068e-01],
       [5.85967086e-01, 8.87248470e-01, 5.62090187e-01, 6.50483563e-01,
   

In [151]:
Data['var_y']

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

Crear un ejemplo de cómo guardar y cargar arreglos de un archivo de texto `.txt`:

    - [NumPy Text files](https://numpy.org/devdocs/reference/routines.io.html#text-files)    
    


In [135]:
x = np.random.randint(10,size=(10,1))
y = np.random.randint(10,size=(10,1))
np.savetxt('NPtxt', x, delimiter=',')   

In [136]:
np.loadtxt('NPtxt', delimiter=',')

array([4., 1., 9., 8., 5., 7., 7., 5., 1., 2.])

Crear una función llamada `estimacionMCO` que lea un archivo CSV con 7 columnas, que corresponden a las variables $(x_{1i}, \ldots, x_{6i})$ y $y_i$. 
    - La función debe computar matricialmente los parámetros del modelo de regresión lineal: $y = X\beta$. 
    - Estos parámetros deben ser devueltos como un arreglo de NumPy. 

    - Utilice la función de lectura de archivos de NumPy.

In [186]:
def estMCO():
    file= str(input("Ingrese el nombre de archivo: "))+".csv"
    data = np.genfromtxt(file,delimiter=',')
    
    x=data[:,0:6]
    y=data[:,6:7]
    
    x_values=(x.T)@x
    y_values=(x.T)@y
    mco =((np.linalg.inv(x_values))@(y_values))
    return mco

In [187]:
print(estMCO())

Ingrese el nombre de archivo: datos
[[ 1.875]
 [-1.   ]
 [ 0.   ]
 [ 1.125]
 [-2.   ]
 [ 0.   ]]
